/**
 * Biodata HTML Templates for PDF generation.
 * Each template produces clean, printable A4 content.
 */

import { BiodataSchema, TemplateId } from "@/types/biodata";

interface TemplateOptions {
  shopName?: string;
  shopLogoUrl?: string;
}

export function getTemplateHtml(
  data: BiodataSchema,
  templateId: TemplateId,
  options?: TemplateOptions
): string {
  switch (templateId) {
    case "simple-classic":
      return simpleClassicTemplate(data, options);
    case "modern-clean":
      return modernCleanTemplate(data, options);
    case "marriage-biodata":
      return marriageBiodataTemplate(data, options);
    default:
      return simpleClassicTemplate(data, options);
  }
}

function baseStyles(): string {
  return `
    * { margin: 0; padding: 0; box-sizing: border-box; }
    body { font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif; color: #333; line-height: 1.6; }
    .page { max-width: 210mm; margin: 0 auto; padding: 20mm; }
    .header { text-align: center; margin-bottom: 20px; padding-bottom: 15px; border-bottom: 2px solid #333; }
    .title { font-size: 24px; font-weight: bold; margin-bottom: 5px; }
    .subtitle { font-size: 14px; color: #666; }
    .photo { width: 120px; height: 150px; border: 1px solid #ccc; margin: 10px auto; display: block; object-fit: cover; }
    .section { margin-bottom: 15px; }
    .section-title { font-size: 16px; font-weight: bold; color: #444; margin-bottom: 8px; padding-bottom: 4px; border-bottom: 1px solid #ddd; }
    .field { display: flex; margin-bottom: 6px; }
    .field-label { font-weight: 600; min-width: 160px; color: #555; }
    .field-value { flex: 1; }
    .shop-info { text-align: center; font-size: 11px; color: #999; margin-top: 30px; padding-top: 10px; border-top: 1px solid #eee; }
  `;
}

function renderField(label: string, value?: string): string {
  if (!value) return "";
  return `<div class="field"><span class="field-label">${label}:</span><span class="field-value">${escapeHtml(value)}</span></div>`;
}

function escapeHtml(text: string): string {
  return text
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;")
    .replace(/'/g, "&#039;");
}

function simpleClassicTemplate(data: BiodataSchema, options?: TemplateOptions): string {
  return `<!DOCTYPE html>
<html>
<head><meta charset="UTF-8"><style>${baseStyles()}</style></head>
<body>
<div class="page">
  <div class="header">
    <div class="title">BIODATA</div>
    ${data.fullName ? `<div class="subtitle">${escapeHtml(data.fullName)}</div>` : ""}
  </div>
  
  ${data.photoUrl ? `<img src="${escapeHtml(data.photoUrl)}" class="photo" alt="Photo" />` : ""}
  
  <div class="section">
    <div class="section-title">Personal Information</div>
    ${renderField("Full Name", data.fullName)}
    ${renderField("Date of Birth", data.dateOfBirth)}
    ${renderField("Age", data.age)}
    ${renderField("Gender", data.gender)}
    ${renderField("Height", data.height)}
    ${renderField("Marital Status", data.maritalStatus)}
    ${renderField("Religion", data.religion)}
    ${renderField("Caste", data.caste)}
  </div>

  <div class="section">
    <div class="section-title">Family Information</div>
    ${renderField("Father's Name", data.fatherName)}
    ${renderField("Mother's Name", data.motherName)}
    ${renderField("Family Details", data.familyDetails)}
  </div>

  <div class="section">
    <div class="section-title">Contact Information</div>
    ${renderField("Address", data.address)}
    ${renderField("City", data.city)}
    ${renderField("State", data.state)}
    ${renderField("Pincode", data.pincode)}
    ${renderField("Phone", data.phone)}
    ${renderField("Email", data.email)}
  </div>

  <div class="section">
    <div class="section-title">Education & Occupation</div>
    ${renderField("Education", data.education)}
    ${renderField("Occupation", data.occupation)}
  </div>

  ${data.hobbies || data.additionalNotes ? `
  <div class="section">
    <div class="section-title">Other Information</div>
    ${renderField("Hobbies", data.hobbies)}
    ${renderField("Additional Notes", data.additionalNotes)}
  </div>` : ""}

  ${options?.shopName ? `<div class="shop-info">Generated by ${escapeHtml(options.shopName)}</div>` : ""}
</div>
</body>
</html>`;
}

function modernCleanTemplate(data: BiodataSchema, options?: TemplateOptions): string {
  return `<!DOCTYPE html>
<html>
<head><meta charset="UTF-8"><style>
  ${baseStyles()}
  body { font-family: 'Helvetica Neue', Arial, sans-serif; }
  .page { padding: 25mm 20mm; }
  .header { border-bottom: 3px solid #2563eb; padding-bottom: 20px; }
  .title { color: #2563eb; font-size: 28px; letter-spacing: 2px; }
  .section-title { color: #2563eb; border-bottom-color: #93c5fd; }
  .field-label { color: #374151; }
  .two-column { display: grid; grid-template-columns: 1fr 1fr; gap: 10px; }
  .photo { border-radius: 8px; border: 2px solid #2563eb; }
</style></head>
<body>
<div class="page">
  <div class="header">
    <div class="title">BIODATA</div>
    ${data.fullName ? `<div class="subtitle" style="font-size:18px;color:#374151;margin-top:5px;">${escapeHtml(data.fullName)}</div>` : ""}
  </div>

  ${data.photoUrl ? `<img src="${escapeHtml(data.photoUrl)}" class="photo" alt="Photo" />` : ""}

  <div class="section">
    <div class="section-title">Personal Details</div>
    <div class="two-column">
      ${renderField("Full Name", data.fullName)}
      ${renderField("Date of Birth", data.dateOfBirth)}
      ${renderField("Age", data.age)}
      ${renderField("Gender", data.gender)}
      ${renderField("Height", data.height)}
      ${renderField("Marital Status", data.maritalStatus)}
      ${renderField("Religion", data.religion)}
      ${renderField("Caste", data.caste)}
    </div>
  </div>

  <div class="section">
    <div class="section-title">Family</div>
    ${renderField("Father's Name", data.fatherName)}
    ${renderField("Mother's Name", data.motherName)}
    ${renderField("Family Details", data.familyDetails)}
  </div>

  <div class="section">
    <div class="section-title">Contact</div>
    <div class="two-column">
      ${renderField("Phone", data.phone)}
      ${renderField("Email", data.email)}
      ${renderField("Address", data.address)}
      ${renderField("City", data.city)}
      ${renderField("State", data.state)}
      ${renderField("Pincode", data.pincode)}
    </div>
  </div>

  <div class="section">
    <div class="section-title">Professional</div>
    ${renderField("Education", data.education)}
    ${renderField("Occupation", data.occupation)}
  </div>

  ${data.hobbies || data.additionalNotes ? `
  <div class="section">
    <div class="section-title">Additional</div>
    ${renderField("Hobbies", data.hobbies)}
    ${renderField("Notes", data.additionalNotes)}
  </div>` : ""}

  ${options?.shopName ? `<div class="shop-info">Generated by ${escapeHtml(options.shopName)}</div>` : ""}
</div>
</body>
</html>`;
}

function marriageBiodataTemplate(data: BiodataSchema, options?: TemplateOptions): string {
  return `<!DOCTYPE html>
<html>
<head><meta charset="UTF-8"><style>
  ${baseStyles()}
  body { font-family: Georgia, 'Times New Roman', serif; }
  .page { padding: 20mm; background: #fffbf0; }
  .header { border-bottom: 2px double #8b4513; padding-bottom: 15px; }
  .title { color: #8b4513; font-size: 26px; font-family: Georgia, serif; }
  .subtitle { color: #a0522d; font-style: italic; }
  .om-symbol { font-size: 32px; color: #d4a017; margin-bottom: 5px; }
  .section-title { color: #8b4513; border-bottom-color: #deb887; font-family: Georgia, serif; }
  .field-label { color: #5d4037; }
  .photo { border: 3px solid #deb887; border-radius: 4px; }
  .decoration { text-align: center; color: #d4a017; font-size: 18px; margin: 10px 0; }
</style></head>
<body>
<div class="page">
  <div class="header">
    <div class="om-symbol">॥ श्री ॥</div>
    <div class="title">Marriage Biodata</div>
    ${data.fullName ? `<div class="subtitle">${escapeHtml(data.fullName)}</div>` : ""}
  </div>

  ${data.photoUrl ? `<img src="${escapeHtml(data.photoUrl)}" class="photo" alt="Photo" />` : ""}

  <div class="decoration">✦ ✦ ✦</div>

  <div class="section">
    <div class="section-title">Personal Information</div>
    ${renderField("Name", data.fullName)}
    ${renderField("Date of Birth", data.dateOfBirth)}
    ${renderField("Age", data.age)}
    ${renderField("Gender", data.gender)}
    ${renderField("Height", data.height)}
    ${renderField("Marital Status", data.maritalStatus)}
    ${renderField("Religion", data.religion)}
    ${renderField("Caste", data.caste)}
  </div>

  <div class="section">
    <div class="section-title">Family Details</div>
    ${renderField("Father's Name", data.fatherName)}
    ${renderField("Mother's Name", data.motherName)}
    ${renderField("Family Details", data.familyDetails)}
  </div>

  <div class="section">
    <div class="section-title">Education & Career</div>
    ${renderField("Education", data.education)}
    ${renderField("Occupation", data.occupation)}
  </div>

  <div class="section">
    <div class="section-title">Contact Details</div>
    ${renderField("Address", data.address)}
    ${renderField("City", data.city)}
    ${renderField("State", data.state)}
    ${renderField("Pincode", data.pincode)}
    ${renderField("Phone", data.phone)}
    ${renderField("Email", data.email)}
  </div>

  ${data.hobbies ? `
  <div class="section">
    <div class="section-title">Hobbies & Interests</div>
    ${renderField("Hobbies", data.hobbies)}
  </div>` : ""}

  ${data.additionalNotes ? `
  <div class="section">
    <div class="section-title">Additional Information</div>
    ${renderField("Notes", data.additionalNotes)}
  </div>` : ""}

  <div class="decoration">✦ ✦ ✦</div>

  ${options?.shopName ? `<div class="shop-info" style="color:#a0522d;">Generated by ${escapeHtml(options.shopName)}</div>` : ""}
</div>
</body>
</html>`;
}
